### ISSUE TITLE
Import package is missing，

### ISSUE THREAD

**Issue by zhanghongyong123456** [sanweiliti/HMP#3]
1.add  import random？
![image](https://user-images.githubusercontent.com/48466610/142791458-a634e15c-a23f-4243-bf51-66074b0d9f00.png)

2.about models download ，I am not sure if the download is correct

![image](https://user-images.githubusercontent.com/48466610/142791971-39cc4bf3-5202-4dd4-a890-1a3791ec3956.png)

![image](https://user-images.githubusercontent.com/48466610/142791880-fef51750-e1fe-43c3-aaac-b9c18bd99413.png)

![image](https://user-images.githubusercontent.com/48466610/142792003-3355de14-e033-4bf2-ba45-6bf3bec1c278.png)

**Comment by sanweiliti** [comment]
Hi,

Thanks for pointing out the import error, and I updated the script.
For the SMPL-X model version, we used SMPL-X v1.0, but you can use v1.1 instead. The difference is that: v1.0 has 10-d shape paramsters and 10-d expression paramsters, while v1.1 has 300-d shape parameters and 100-d expression parameters. If you use v1.1, just use the first 10 dimensions of shape parameters and first 10 dimensions of expression parameters.

**Comment by zhanghongyong123456** [comment]
> Hi,
> 
> Thanks for pointing out the import error, and I updated the script. For the SMPL-X model version, we used SMPL-X v1.0, but you can use v1.1 instead. The difference is that: v1.0 has 10-d shape paramsters and 10-d expression paramsters, while v1.1 has 300-d shape parameters and 100-d expression parameters. If you use v1.1, just use the first 10 dimensions of shape parameters and first 10 dimensions of expression parameters.

thanks，i try it
