### ISSUE TITLE
Fitting on AMASS     python opt_amass_perframe.py   about  error  

### ISSUE THREAD

**Issue by zhanghongyong123456** [sanweiliti/HMP#4]
![image](https://user-images.githubusercontent.com/48466610/142838601-60e9d5cf-6b90-47bb-b818-261410edf27b.png)
![image](https://user-images.githubusercontent.com/48466610/142838881-41d5bf2d-c71c-4b47-8636-8400ba5223a0.png)

**Comment by sanweiliti** [comment]
Hi,
you need to unzip the amass data before running the scripts.

**Comment by zhanghongyong123456** [comment]
> Hi, you need to unzip the amass data before running the scripts.

ok

**Comment by FengWei2000** [comment]
> > Hi, you need to unzip the amass data before running the scripts.
> 
> ok

I have the same problem as you, but I have unzipped the file.May I see the contents and path of your folder?

**Comment by FengWei2000** [comment]
> > > Hi, you need to unzip the amass data before running the scripts.
> > 
> > 
> > ok
> 
> I have the same problem as you, but I have unzipped the file.May I see the contents and path of your folder?

Oh, I used the smPL-H dataset and the result was fine
