### ISSUE TITLE
Questions about how to obtain mask_markers

### ISSUE THREAD

**Issue by WeiCaike** [sanweiliti/HMP#5]
Hi,
Recently I cited your paper and code to do some research.  If I want to train and test on my own dataset, how can I get the mask_markers?
Thank you.

**Comment by sanweiliti** [comment]
Hi,

Thanks for your interest in our work. To get the mask for markers, we use the initial fitting results from original PROX dataset, and render the fitted bodies, and the 3D scene separately from the camera view, which gives depth information for each pixel. If the depth of body marker/body joint is larger then the scene vertex at the same 2D pixel location, we consider it as occluded.

**Comment by WeiCaike** [comment]
> Hi,
> 
> Thanks for your interest in our work. To get the mask for markers, we use the initial fitting results from original PROX dataset, and render the fitted bodies, and the 3D scene separately from the camera view, which gives depth information for each pixel. If the depth of body marker/body joint is larger then the scene vertex at the same 2D pixel location, we consider it as occluded.

Thank you for your response.
