### ISSUE TITLE
How can I make a video like the one in the example?

### ISSUE THREAD

**Issue by FengWei2000** [sanweiliti/HMP#6]
![Snipaste_2021-12-23_19-24-00](https://user-images.githubusercontent.com/47074522/147233679-4403609d-3581-4db2-a84a-19af96412b3d.jpg)

**Comment by sanweiliti** [comment]
Could you elaborate your question?

**Comment by FengWei2000** [comment]
> Could you elaborate your question?

What I want to ask is, when I have a normal video, how do I get a video that looks like the one in the picture, where the human body is covered with a little white model based on the original video. Thank you very much!

**Comment by sanweiliti** [comment]
Hi,
you can use temp_prox/renderer.py and set the 'rendering_mode' to 'body'. It will render this body from the camera view and overlay it on the input RGB image.
